import type { Metadata } from "next";
import "./globals.css";
import 'remixicon/fonts/remixicon.css';
import { ChildrenProps } from "@/src/types";
import localFont from 'next/font/local';
import { NoSSRProviders } from "@/src/components/noSSRProviders";

const mainFont = localFont({
  src: [
    { path: '../public/fonts/FiraCode.ttf' }
  ],
  variable: '--font-main',
  preload: true,
  fallback: [
    "ui-monospace",
    "SFMono-Regular",
    "Menlo",
    "Monaco",
    "Consolas",
    "Liberation Mono",
    "Courier New",
    "monospace"
  ],
  display: 'block'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: ChildrenProps) {
  return (
    <html lang="en" suppressHydrationWarning className={mainFont.variable}>
      <body>
        <NoSSRProviders>
          {children}
        </NoSSRProviders>
      </body>
    </html>
  );
}
